version: '3.7'

services:
  postgres:
    image: postgres:14

    restart: always

    container_name: 'postgres_container'

    ports:
      - '5432:5432'

    volumes:
      - ./db_data:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: postgres

      POSTGRES_PASSWORD: postgres

      POSTGRES_DB: bank

    expose:
      - '5432'
